                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // js/algorithms.js

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * First Fit: mengalokasikan setiap proses di blok pertama yang muat.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @param {number[]} block_sizes - Array ukuran blok memori yang tersedia.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @param {number[]} process_sizes - Array ukuran proses yang akan dialokasikan.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @returns {{allocations: object[], finalBlocks: number[], blockStates: number[][]}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * Detail alokasi, status akhir blok, dan snapshot status blok.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export function firstFit(block_sizes, process_sizes) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let available = [...block_sizes]; // Buat salinan dangkal untuk mensimulasikan status memori
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const allocations = []; // Menyimpan detail setiap alokasi (proses, blok, ukuran sisa)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const states = []; // Variabel 'states' diinisialisasi di sini

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              process_sizes.forEach((psize, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let allocated = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (let j = 0; j < available.length; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Periksa apakah blok saat ini cukup besar untuk proses
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (available[j] >= psize) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    available[j] -= psize; // Alokasikan memori
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    allocations.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      processId: `P${i+1}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      processSize: psize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      blockId: `B${j+1}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      allocatedSize: psize, // Ukuran yang benar-benar dialokasikan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      remainingBlockSize: available[j],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      blockIndex: j // Simpan indeks blok asli untuk visualisasi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    allocated = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break; // Pindah ke proses berikutnya setelah menemukan kecocokan pertama
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!allocated) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Jika tidak ada blok yang ditemukan, proses tidak dialokasikan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  allocations.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processId: `P${i+1}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processSize: psize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    blockId: 'Unallocated'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Catat status blok saat ini setelah upaya proses ini
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                states.push([...available]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Mengembalikan objek dengan 'blockStates' yang merujuk ke array 'states' yang telah dideklarasikan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return { allocations, finalBlocks: available, blockStates: states };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * Best Fit: mengalokasikan setiap proses di blok terkecil yang muat.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @param {number[]} block_sizes - Array ukuran blok memori yang tersedia.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @param {number[]} process_sizes - Array ukuran proses yang akan dialokasikan.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @returns {{allocations: object[], finalBlocks: number[], blockStates: number[][]}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * Detail alokasi, status akhir blok, dan snapshot status blok.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export function bestFit(block_sizes, process_sizes) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let available = [...block_sizes];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const allocations = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const states = []; // Variabel 'states' diinisialisasi di sini

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              process_sizes.forEach((psize, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let bestIdx = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let min_remaining_size = Infinity;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (let j = 0; j < available.length; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (available[j] >= psize) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let remaining_size = available[j] - psize;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (remaining_size < min_remaining_size) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      min_remaining_size = remaining_size;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      bestIdx = j;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (bestIdx !== -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  available[bestIdx] -= psize;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  allocations.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processId: `P${i+1}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processSize: psize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    blockId: `B${bestIdx+1}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    allocatedSize: psize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    remainingBlockSize: available[bestIdx],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    blockIndex: bestIdx
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  allocations.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processId: `P${i+1}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processSize: psize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    blockId: 'Unallocated'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                states.push([...available]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return { allocations, finalBlocks: available, blockStates: states };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * Worst Fit: mengalokasikan setiap proses di blok terbesar yang muat.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @param {number[]} block_sizes - Array ukuran blok memori yang tersedia.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @param {number[]} process_sizes - Array ukuran proses yang akan dialokasikan.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @returns {{allocations: object[], finalBlocks: number[], blockStates: number[][]}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * Detail alokasi, status akhir blok, dan snapshot status blok.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export function worstFit(block_sizes, process_sizes) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let available = [...block_sizes];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const allocations = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const states = []; // Variabel 'states' diinisialisasi di sini

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              process_sizes.forEach((psize, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let worstIdx = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let max_remaining_size = -1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (let j = 0; j < available.length; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (available[j] >= psize) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let remaining_size = available[j] - psize;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (remaining_size > max_remaining_size) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      max_remaining_size = remaining_size;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      worstIdx = j;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (worstIdx !== -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  available[worstIdx] -= psize;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  allocations.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processId: `P${i+1}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processSize: psize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    blockId: `B${worstIdx+1}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    allocatedSize: psize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    remainingBlockSize: available[worstIdx],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    blockIndex: worstIdx
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  allocations.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processId: `P${i+1}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processSize: psize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    blockId: 'Unallocated'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                states.push([...available]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return { allocations, finalBlocks: available, blockStates: states };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
